# -*- coding: utf-8 -*-
"""app_reduced_modified

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gWwD7UGPpai8Y8DVgitgB5aA6M_JeFck
"""

#!/usr/bin/env python
# coding: utf-8

# In[ ]:



import streamlit as st
import joblib
import pandas as pd

# Load presaved model from athena's code
@st.cache_resource
def load_model():
    return joblib.load("logreg_model_reduced.pkl")  # update filename if needed

model = load_model()

#To transform the model’s raw probability into clear, clinically meaningful categories,
#which is essential for good CDS design. Instead of giving just a number, it has classified
#risk as high, moderate, or low using thresholds from ROC.
#Gave a short, actionable recommendation, like CDS principles have said by making the
#output easier to interpret, quicker to act on, and better integrated into real clinical workflows.

def categorize_risk(probability):
    if probability >= 0.30:
        return (
            "Warning 'High risk' ",
            "This patient has an high estimated 10 year CHD risk. "
            "Further cardiovascular evaluation, lipid management, "
            "and lifestyle intervention is needed.")
    elif probability >= 0.15:
        return (
            "Moderate risk",
            "This patient is in the moderate risk range. "
            "Consider counseling on diet, activity, discountinue smoking, "
            "and monitoring cardiovascular indicators.")
    else:
        return (
            "Low risk",
            "This patient has a low estimated CHD risk. "
            "Continue routine care and reinforcement of healthy habits.")


st.title("10 Year CHD Risk Estimator")

# CDS tool must immediately tell the user what it is, what it does, and how the prediction is generated
st.write("""This tool is a **Prototype Clinical Decision Support Application**.
It uses a logistic regression model trained on the Framingham dataset to estimate
**10 year coronary heart disease risk** using routinely available predictors.
""")

st.write("Please enter patient information below:")

#Using two columns makes the CDS tool faster and more natural for clinicians to use.
#reduces scrolling, keeps the entire form visible on one screen, and groups related information
#in a way that mirrors real clinical format,demographics and behaviors on the left, vitals and labs on the right.
demographics, vitals = st.columns(2)

with demographics:
    sex = st.selectbox("Sex", ["Female", "Male"])
    male = 1 if sex == "Male" else 0

    age = st.number_input("Age (years)", min_value=20, max_value=100, value=50)

    cigsPerDay = st.number_input(
        "Cigarettes per day",
        min_value=0,
        max_value=70,
        value=0)

with vitals:
    totChol = st.number_input(
        "Total Cholesterol (mg/dL)",
        min_value=100,
        max_value=700,
        value=200)

    sysBP = st.number_input(
        "Systolic Blood Pressure (mmHg)",
        min_value=80,
        max_value=300,
        value=120)

    glucose = st.number_input(
        "Fasting Glucose (mg/dL)",
        min_value=40,
        max_value=400,
        value=90)

prevalentStroke = st.selectbox("History of Stroke?", ["No", "Yes"])
prevalentStroke = 1 if prevalentStroke == "Yes" else 0


# build dataframe
input_df = pd.DataFrame({
    "male": [male],
    "age": [age],
    "cigsPerDay": [cigsPerDay],
    "prevalentStroke": [prevalentStroke],
    "totChol": [totChol],
    "sysBP": [sysBP],
    "glucose": [glucose],})


if st.button("Predict 10-Year CHD Risk"):

      # --- Clinical Data Quality Checks (CDS safety feature) ---
    warnings = []
    if totChol > 400:
        warnings.append("Total cholesterol is extremely high — verify lab result.")
    if sysBP < 80 or sysBP > 200:
        warnings.append("Blood pressure is outside expected clinical range — verify measurement.")
    if glucose < 50 or glucose > 300:
        warnings.append("Glucose level is unusual — confirm with lab values.")

    for w in warnings:
        st.warning(w)


    probability = model.predict_proba(input_df)[0, 1]
    risk_percent = probability * 100

    st.subheader("Risk Estimate")
    st.metric("10-Year CHD Probability", f"{risk_percent:.1f}%")


# Risk category function to label the patient as high, moderate, or low risk, and then
#displays that category (warning, info, success), which mirrors real
#CDS systems and makes severity easy to interpret quickly.
    category, message = categorize_risk(probability)

    if category == "High risk":
        st.warning(f"**{category}:** {message}")
    elif category == "Moderate risk":
        st.info(f"**{category}:** {message}")
    else:
        st.success(f"**{category}:** {message}")
    st.caption("Thresholds chosen based on our project’s ROC ")


    # CDS tools must deliver information quickly.
    # A visual gauge allows clinicians to interpret risk instantly without reading long text.
    #This reduces cognitive load and improves usability.
    st.write("### Visual Risk Indicator")
    st.progress(min(probability, 1.0))


    # Disclaimer
    st.markdown("""
    ---
    ### Disclaimer
    This tool is a course project prototype built for educational purposes.
    It is **not** validated for clinical use and should not replace clinical judgment,
    guidelines, or clinician decision making.""")

    summary = f"""
    10-Year CHD Risk Prediction Summary
    -----------------------------------
    Predicted probability: {risk_percent:.1f}%
    Risk category: {category}

    Recommended Actions:
    {message}

    Inputs:
    Sex: {sex}
    Age: {age}
    Cigarettes/day: {cigsPerDay}
    Total Cholesterol: {totChol}
    Systolic BP: {sysBP}
    Glucose: {glucose}
    Stroke history: {prevalentStroke}
    """

    st.download_button("Download Risk Summary", summary)